INSERT INTO owners (firstname, middlename, lastname, suffix, organization, lot_number, lot_descriptor, section) VALUES
('Edward', 'A', 'Eberman', NULL, NULL, '24', 'Western Third of Northern Half', 'L'),
('Fazil', 'B', 'Erdogan', NULL, NULL, '52', 'Western Third of Southern Half', 'L'),
('Barbara', NULL, 'Erdogan', NULL, NULL, '52', 'Western Third of Southern Half', 'L'),
('Karl', NULL, 'Forster', NULL, NULL, '72', 'Western Third of Northern Half', 'L'),
('Mary', NULL, 'Forster', NULL, NULL, '72', 'Western Third of Northern Half', 'L'),
('Mae', NULL, 'Fulmer', NULL, NULL, '53', 'Eastern Portion of Northern Half', 'L'),
('Samuel', 'W', 'Gates', NULL, NULL, '70', 'Northern Half', 'L'),
('Joseph', 'J', 'Gebhard', NULL, NULL, '13', 'Center Third of Northern Half', 'L'),
('Ella', 'C', 'Gebhard', NULL, NULL, '13', 'Center Third of Northern Half', 'L'),
('Henry', NULL, 'Goebel', NULL, NULL, '54', 'Eastern End of Northern Half', 'L'),
('Charles', 'A', 'Haehnle', NULL, NULL, '77', 'Southern Half', 'L'),
('Alice', 'F', 'Haehnle', NULL, NULL, '77', 'Southern Half', 'L'),
('Samuel', 'R', 'Clarke', NULL, NULL, '43', 'Eastern Third of Southern Half', 'L'),
('Sinclair', 'W', 'Chiles', NULL, NULL, '44', 'Western Half of Eastern Third of Southern Half', 'L'),
('Ethel', 'H', 'Chiles', NULL, NULL, '44', 'Western Half of Eastern Third of Southern Half', 'L'),
('Frederick', 'W', 'Chillingworth', 'III', NULL, '13', 'Eastern Sixth of Southern Half', 'L'),
('Madia', NULL, 'Chiles', NULL, NULL, '55a1', NULL, 'L'),
('Sloane', NULL, 'Chiles', NULL, NULL, '55a1', NULL, 'L'),
('Leila', NULL, 'Chiles', NULL, NULL, '55a1', NULL, 'L'),
('Marilyn', NULL, 'Brown', NULL, NULL, '40', 'Eastern Third of Western Half of Southern Half', 'L'),
('Jacob', 'W', 'Beidler', NULL, NULL, '9', 'Southern Half', 'L'),
('Hattie', 'M', 'Beidler', NULL, NULL, '9', 'Southern Half', 'L'),
('Ida', 'C', 'Beidleman', NULL, NULL, '10', 'Western End of Northern Half', 'L'),
('Edgar', 'R', 'Beidleman', NULL, NULL, '9', 'Northern Half', 'L'),
('Frederick', 'T', 'Beckel', NULL, NULL, '14', 'Eastern Two Thirds', 'L'),
('Helen', 'E', 'Beckel', NULL, NULL, '14', 'Eastern Two Thirds', 'L'),
('Edith', NULL, 'Beckel-Dalziel', NULL, NULL, '14', 'Eastern Two Thirds', 'L'),
('Peter', 'J', 'Behrens', NULL, NULL, '12', 'Center Third of Northern Half', 'L'),
('Judy', NULL, 'Antry', NULL, NULL, '21', 'Center Third of Northern Half', 'L'),
('Charles', 'L', 'Diehl', NULL, NULL, '48', 'Eastern End of Southern Half', 'L'),
('Charles', 'F', 'Donchez', NULL, NULL, '15', 'Western Two Thirds of Eastern Portion of Southern Half', 'L'),
('Amalia', 'J', 'Donchez', NULL, NULL, '15', 'Western Two Thirds of Eastern Portion of Southern Half', 'L');
